#pragma once
#include <cmath>
#include <cstdlib>
#include <array>

namespace LegacyCamera {
constexpr int AngleMask=0x7ff;
constexpr int AngleUnitsPerTurn=2048;
constexpr float Pi=3.14159265358979323846f;
constexpr float TwoPi=6.2831853071795864769f;
constexpr float RadiansPerUnit=TwoPi/float(AngleUnitsPerTurn);

inline int wrapAngle(int value){ return value&AngleMask; }
inline float radians(int value){ return float(wrapAngle(value))*RadiansPerUnit; }

// Confirmed normal gameplay X/Z tracking globals (DA58 / DA60).
inline float trackedX(float playerWorldX){ return (playerWorldX-.4f)*.5f+.45f; }
inline float trackedZ(float playerWorldZ){ return (playerWorldZ-.4f)*.5f+.35f; }

// Exact 3x3 basis generated by AirXonix.wrp.exe:0x40C250. The legacy
// function receives three 0..2047 angles at +14/+18/+1C; below they are named
// angle1/angle2/angle3 in that call order. The resulting matrix has determinant
// -1 because the old renderer folds a Y-axis reflection into the camera basis.
struct Basis3 {
    float m00,m01,m02;
    float m10,m11,m12;
    float m20,m21,m22;
};

inline Basis3 basis(int angle1,int angle2,int angle3){
    const float c=radians(angle1);
    const float b=radians(angle2);
    const float a=radians(angle3);
    const float sa=std::sin(a), ca=std::cos(a);
    const float sb=std::sin(b), cb=std::cos(b);
    const float sc=std::sin(c), cc=std::cos(c);
    // Address order 0x53B698..0x53B6B8.
    return {
        ca*cc + sa*sb*sc,   -sa*cb,                 -ca*sc + sa*sb*cc,
        ca*sb*sc - sa*cc,   -ca*cb,                  ca*cc*sb + sa*sc,
        cb*sc,               sb,                     cb*cc
    };
}


struct CameraPoint { float x,y,depth; };
struct ClipDistances { float left,right,top,bottom; };
struct ProjectionState {
    float halfWidth;
    float halfHeight;
    float focal;
    float leftSlope;
    float rightSlope;
    float topSlope;
    float bottomSlope;
};

inline ProjectionState projectionState(int width,int height){
    const int hw=width/2, hh=height/2;
    const float fw=float(hw>0?hw:1);
    return {float(hw),float(hh),fw,
            -float(hw-1)/fw, float(hw-1)/fw,
            -float(hh-1)/fw, float(hh-1)/fw};
}

// Exact row-dot transform performed at 0x40C407..0x40C46F after object/world
// translation has already been made relative to camera position.
inline CameraPoint transformRelative(const Basis3& m,float x,float y,float z){
    return {
        x*m.m00 + y*m.m01 + z*m.m02,
        x*m.m10 + y*m.m11 + z*m.m12,
        x*m.m20 + y*m.m21 + z*m.m22
    };
}

inline ClipDistances clipDistances(const ProjectionState& p,const CameraPoint& v){
    return {
        v.x - p.leftSlope*v.depth,
        p.rightSlope*v.depth - v.x,
        v.y - p.topSlope*v.depth,
        p.bottomSlope*v.depth - v.y
    };
}

struct ScreenPoint { float x,y,depth,rhw; };
inline ScreenPoint project(const ProjectionState& p,const CameraPoint& v){
    const float rhw=1.f/v.depth;
    return {v.x*p.focal*rhw+p.halfWidth,
            v.y*p.focal*rhw+p.halfHeight,
            v.depth,rhw};
}

struct GameplayCameraState {
    float x,y,z;
    int angle1,angle2,angle3;
};

// Normal gameplay constants initialized at 0x418D6A..0x418D95 and passed to
// 0x40C250 by 0x41A1EA..0x41A1F9. DA58/DA60 are the exact player-tracking
// formulas already exposed above; effect displacement DAD4 moves Y by
// -1.1*d and Z by +d; camera shake is added to angle3/DA70.
inline std::array<float,3>& debugFocus(){static std::array<float,3> v{-1.f,-1.f,0.f};return v;}
inline GameplayCameraState gameplayState(float playerWorldX,float playerWorldZ,
                                         float displacement,int angle3Offset){
    // debug-only close-up: AIRXONIX_DEBUG_CAM=<distance> orbits the player.
    static const float dbg=[](){const char* e=std::getenv("AIRXONIX_DEBUG_CAM");return e?float(std::atof(e)):0.f;}();
    if(dbg>0.f){const float fx=debugFocus()[0]>=0.f?debugFocus()[0]:playerWorldX,fz=debugFocus()[0]>=0.f?debugFocus()[1]:playerWorldZ;
        return {fx,0.008f+debugFocus()[2]+0.8f*dbg,fz-0.6f*dbg,0,-302,angle3Offset};}
    return {trackedX(playerWorldX),
            0.103f-1.1f*displacement,
            trackedZ(playerWorldZ)+displacement,
            0,-302,angle3Offset};
}

// 0x41AC08..0x41AD87 normal inter-level tracking.  X/Z retain the ordinary
// half-distance follow while camera Y rises at half the Xonix presentation Y
// relative to the 0.013 reference plane. DAD4 keeps its normal displacement.
inline GameplayCameraState interLevelState(float playerWorldX,float playerWorldY,float playerWorldZ,
                                           float displacement,int angle3Offset){
    return {trackedX(playerWorldX),
            0.103f+0.5f*(playerWorldY-0.013000000268220901f)-1.1f*displacement,
            trackedZ(playerWorldZ)+displacement,
            0,-302,angle3Offset};
}



// 0x41B732..0x41B79E finale camera tracking. Unlike normal gameplay the
// camera rises with Xonix and also backs away by (height-.008) along Z.
inline GameplayCameraState finaleState(float playerWorldX,float playerWorldY,float playerWorldZ,
                                       float displacement,int angle3Offset){
    return {trackedX(playerWorldX),
            0.103f+0.5f*(playerWorldY-0.013000000268220901f)-1.1f*displacement,
            trackedZ(playerWorldZ)-(playerWorldY-0.00800000037997961f)+displacement,
            0,-302,angle3Offset};
}

// 0x41C370 + 0x41C7D9 death-camera tracking. Before the 0x418200 burst,
// DA5C follows the airborne death object at half its vertical displacement;
// after the burst DA5C is .103 because presentation Y is detached to .5.
inline GameplayCameraState deathState(float worldX,float worldY,float worldZ,
                                      bool postBurst,int angle3Offset){
    const float y=postBurst?0.103f:(0.103f+(worldY-0.00800000037997961f)*0.5f);
    return {trackedX(worldX),y,trackedZ(worldZ),0,-302,angle3Offset};
}

}
