#include "level.hpp"
#include <algorithm>
#include <stdexcept>
#include "legacy_levels.inc"

namespace {
LevelRecord decode(const unsigned char* b) {
    LevelRecord r;
    r.enemySpeed=b[0]; r.enemyTypeACount=b[1]; r.enemyTypeBCount=b[2];
    r.crawlerSpeed=b[3]; r.crawlerCount=b[4]; r.specialHoming=b[5];
    r.specialEraser=b[6]; r.legacyCheckByte=b[7];
    for (int i=0;i<5;++i) r.shapeType[i]=b[8+i];
    for (int i=0;i<5;++i) r.shapeX[i]=b[13+i];
    for (int i=0;i<5;++i) r.shapeY[i]=b[18+i];
    for (int i=0;i<5;++i) r.shapeRadius[i]=b[23+i];
    return r;
}
}

LevelDatabase::LevelDatabase() {
    modes_.resize(5);
    for (std::size_t m=0;m<5;++m) {
        modes_[m].name = kLegacyModeNames[m];
        for (unsigned i=0;i<kLegacyModeCounts[m];++i)
            modes_[m].levels.push_back(decode(kLegacyLevelBytes[kLegacyModeStarts[m]+i]));
    }
}

LevelDatabase::LevelDatabase(const std::vector<std::uint8_t>& soundInf) {
    const std::size_t minimum=LegacyModeResourceTrace::levelRecordsOffset+LegacyModeResourceTrace::totalLevels*LegacyModeResourceTrace::levelRecordBytes;
    if(soundInf.size()<minimum || soundInf[0]!=LegacyModeResourceTrace::modeCount) throw std::runtime_error("invalid SOUNDINF resource");
    auto le32=[&](std::size_t o){return unsigned(soundInf[o])|(unsigned(soundInf[o+1])<<8)|(unsigned(soundInf[o+2])<<16)|(unsigned(soundInf[o+3])<<24);};
    modes_.resize(LegacyModeResourceTrace::modeCount);
    for(std::size_t m=0;m<modes_.size();++m){
        // r324 DIRECT RESOURCE CONTRACT: 0x4230F0 copies five fixed 12-byte
        // CP1251 mode-name fields from SOUNDINF to 0x25B5BCC. Consumers such
        // as Records use those runtime bytes, so do not replace them with the
        // default Russian constants when an original/custom resource is loaded.
        const std::size_t nameOff=LegacyModeResourceTrace::modeNamesOffset+m*LegacyModeResourceTrace::modeNameBytes;
        std::size_t nameLen=0;
        while(nameLen<LegacyModeResourceTrace::modeNameBytes && soundInf[nameOff+nameLen]!=0)++nameLen;
        modes_[m].name.assign(reinterpret_cast<const char*>(soundInf.data()+nameOff),nameLen);
        const unsigned count=le32(LegacyModeResourceTrace::modeCountsOffset+m*4);
        const unsigned start=le32(LegacyModeResourceTrace::modeStartsOffset+m*4);
        if(start+count>LegacyModeResourceTrace::totalLevels) throw std::runtime_error("invalid SOUNDINF mode range");
        for(unsigned i=0;i<count;++i){const std::size_t off=LegacyModeResourceTrace::levelRecordsOffset+std::size_t(start+i)*LegacyModeResourceTrace::levelRecordBytes;modes_[m].levels.push_back(decode(soundInf.data()+off));}
    }
}

const LevelRecord& LevelDatabase::level(std::size_t mode, std::size_t index) const {
    if (mode>=modes_.size() || index>=modes_[mode].levels.size()) throw std::out_of_range("AirXonix level");
    return modes_[mode].levels[index];
}

std::size_t LevelDatabase::totalLevels() const {
    std::size_t n=0; for (const auto& m:modes_) n+=m.levels.size(); return n;
}


std::vector<std::uint8_t> makeCleanroomSoundInf() {
    // r205 clean-room fallback.  These records are generated from a new
    // deterministic progression, not from legacy_levels.inc or the commercial
    // SOUNDINF resource.  The on-disk assets/raw/SOUNDINF.bin is generated by
    // tools/generate_cleanroom_resources.py with the same contract.
    constexpr std::array<unsigned,5> counts{{7,15,20,20,20}};
    constexpr std::array<unsigned,5> starts{{0,7,22,42,62}};
    std::vector<std::uint8_t> data(LegacyModeResourceTrace::resourceBytes,0u);
    auto put32=[&](std::size_t o,unsigned v){data[o]=std::uint8_t(v);data[o+1]=std::uint8_t(v>>8);data[o+2]=std::uint8_t(v>>16);data[o+3]=std::uint8_t(v>>24);};
    put32(0,5u);
    constexpr std::array<std::array<std::uint8_t,12>,5> names{{
        {{207,208,206,209,210,192,223,0,0,0,0,0}}, // ПРОСТАЯ (CP1251)
        {{202,203,192,209,209,200,202,192,0,0,0,0}}, // КЛАССИКА
        {{204,206,196,197,208,205,0,0,0,0,0,0}}, // МОДЕРН
        {{213,192,208,196,0,0,0,0,0,0,0,0}}, // ХАРД
        {{221,202,209,210,208,200,204,0,0,0,0,0}} // ЭКСТРИМ
    }};
    for(std::size_t m=0;m<5;++m){
        for(std::size_t i=0;i<12;++i)data[LegacyModeResourceTrace::modeNamesOffset+m*12+i]=names[m][i];
        put32(LegacyModeResourceTrace::modeCountsOffset+m*4,counts[m]);put32(LegacyModeResourceTrace::modeStartsOffset+m*4,starts[m]);
    }
    struct Shape{std::uint8_t t,x,y,r;};
    const std::array<std::array<Shape,5>,8> templates{{
        {{{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
        {{{1,32,32,5},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
        {{{2,32,32,8},{0,0,0,0},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
        {{{1,18,18,4},{1,46,46,4},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
        {{{2,18,46,6},{2,46,18,6},{0,0,0,0},{0,0,0,0},{0,0,0,0}}},
        {{{1,16,32,3},{1,48,32,3},{2,32,32,5},{0,0,0,0},{0,0,0,0}}},
        {{{2,12,12,4},{2,52,12,4},{2,12,52,4},{2,52,52,4},{0,0,0,0}}},
        {{{1,20,20,3},{1,44,20,3},{1,20,44,3},{1,44,44,3},{2,32,32,4}}}
    }};
    std::size_t idx=0;
    for(unsigned mode=0;mode<5;++mode){
        for(unsigned i=0;i<counts[mode];++i,++idx){
            const unsigned speed=std::min(18u,8u+mode*2u+i/4u);
            const unsigned crawlerSpeed=std::min(18u,8u+mode*2u+i/5u);
            const unsigned total=std::min(8u,2u+mode+i/5u);
            unsigned a=0,b=0; switch((i+mode)%3u){case 0:a=total;break;case 1:b=std::max(1u,total-1u);break;default:a=(total+1u)/2u;b=total/2u;break;}
            const unsigned crawlers=std::min(6u,1u+mode+i/6u);
            unsigned homing=0,eraser=0;
            if(mode>=2u && (i+mode)%5u==1u)homing=std::min(14u,5u+mode*2u+i/6u);
            if(mode>=2u && (i+2u*mode)%6u==2u)eraser=std::min(15u,6u+mode*2u+i/7u);
            if(mode>=3u && i%11u==10u){homing=std::min(15u,8u+mode);eraser=std::min(15u,8u+mode);}
            const auto& sh=templates[(i+mode*2u)%templates.size()];
            const std::size_t o=LegacyModeResourceTrace::levelRecordsOffset+idx*LegacyModeResourceTrace::levelRecordBytes;
            data[o+0]=std::uint8_t(speed);data[o+1]=std::uint8_t(a);data[o+2]=std::uint8_t(b);data[o+3]=std::uint8_t(crawlerSpeed);data[o+4]=std::uint8_t(crawlers);data[o+5]=std::uint8_t(homing);data[o+6]=std::uint8_t(eraser);data[o+7]=std::uint8_t((mode*29u+i*17u)&0x7fu);
            for(std::size_t j=0;j<5;++j){data[o+8+j]=sh[j].t;data[o+13+j]=sh[j].x;data[o+18+j]=sh[j].y;data[o+23+j]=sh[j].r;}
        }
    }
    return data;
}

float legacyDifficultyScale(float configValue) {
    return (configValue - 800.0f) * 0.00025f + 1.0f;
}

float legacyScoreMultiplier(const LevelRecord& r, float d) {
    const float base =
        (static_cast<float>(r.crawlerSpeed) * r.crawlerCount) * 0.7f +
        (static_cast<float>(r.enemySpeed) * r.enemyTypeBCount) * 1.5f +
        (static_cast<float>(r.specialHoming) + r.specialEraser) * 3.0f +
        (static_cast<float>(r.enemySpeed) * r.enemyTypeACount) + 10.0f;
    return base * d * d * 0.05f;
}
